#! /bin/sh
# /etc/init.d/transferStartup
 
### BEGIN INIT INFO
# Provides:          transferStartup
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: start transfer.py from boot
# Description:       A script which will start transfer.py from boot and stop upon shut-down
### END INIT INFO
 
# Put any commands you always want to run here.
 
case "$1" in
	start)
		echo "Starting transfer.py"
		# run the program you want to start
		sudo python3 '/home/pi/Desktop/PetCar Repo/PetCar3_2/transfer.py'
	;;
	stop)
		echo "Stopping example"
		# end the program you want to stop
		killall python3
	;;
	*)

 echo "Usage: /etc/init.d/transferStartup {start|stop}"
 exit 1
 ;;
esac
